### ISSUE TITLE
.net framework 4.8

### ISSUE THREAD

**Issue by merc74** [maxbl4/RfidDotNet#4]
I'm trying to use your library in .net framework 4.8 WPF project. 
But it's not working, Your Demo project works fine but it's in console app.
Would you be able to help so I can figure out what needs to be done to have this working in a WPF application?

**Comment by maxbl4** [comment]
Hi, I'm actually using this lib in a .NetFramework 4.8 WPF application without any special configuration. Can you try to create new WPF app and setup the lib, like it's shown in the demo? If still have issues, you could upload your version and post a link, so I review the sources

**Comment by merc74** [comment]
Hi, thanks for the quick response. 
Using Visual Studio 2019.
I downloaded your GitHub, and then tried to create a new project within your Git solution. I created a WPF with .NetFramework 4.8 WPF application, I was able to add all the references to the other projects and it compiles clean.
I basically copied what you have in your demo project into a Button within the WPF application. 
When running it, it goes to the "stream.Start().Wait();" then within your AlienTech project when trying to do the task connect(); it returns an error cannot find assembly reference.

Also when trying to install the maxbl4.Infrastructure, 1.0.44 it returns an error:
Could not install package 'maxbl4.Infrastructure 1.0.44'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.		

I cannot find this project in your GIT: maxbl4.Infrastructure 

Yes if you could load a WPF Demo it would be amazing and I can figure out what I'm doing wrong.
Thanks for your help

**Comment by maxbl4** [comment]
Try to create new separate project, add only nuget maxbl4.RfidDotNet.AlienTech (or GenericSerial if you use it), all the deps should load transiently

**Comment by merc74** [comment]
It's not working at all for me
It's for sure my fault.
Here is a link of the app: https://drive.google.com/file/d/15sNRfjW6SH3TWV6lYu05PpfAQtGsk9SF/view?usp=sharing

I have to add these:
using maxbl4.RfidDotNet.Infrastructure;
using maxbl4.RfidDotNet;
using maxbl4.RfidDotNet.AlienTech.Extensions;

Basically it cannot find this:
public class ReconnectingAlienReaderProtocol : IUniversalTagStream
private async Task Connect()

This is the error I get :
{"Could not load file or assembly 'Infrastructure, Version=1.0.42.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.":"Infrastructure, Version=1.0.42.0, Culture=neutral, PublicKeyToken=null"}

**Comment by merc74** [comment]
Alright after adding your package maxbl4.Infrastructure 1.0.42, it started to go further, but it creates the following errors.
Within the same VS solutions, I change the startup to your Demo console app, and everything works fine.

[14:18:59 INF] ConnectAndLogin
[14:18:59 INF] Connect with 192.168.0.47:23 timeout 5000
'WpfApp2.exe' (CLR v4.0.30319: WpfApp2.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Sockets\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Sockets.dll'. Module was built without symbols.
[14:18:59 DBG] Connect task started
[14:18:59 DBG] Connect task acquired semaphore
[14:18:59 DBG] Connect task socket connected
[14:18:59 INF] Constructed
[14:18:59 DBG] Connect task completed
[14:19:00 DBG] Send 

[14:19:00 DBG] Send acquired semaphore
[14:19:00 DBG] Send completed
[14:19:00 DBG] Read start
[14:19:00 DBG] Read acquired semaphore
[14:19:00 DBG] Read completed
[14:19:00 INF] Keepalive success
[14:19:01 DBG] Send 

[14:19:01 DBG] Send acquired semaphore
[14:19:01 DBG] Send completed
[14:19:01 DBG] Read start
[14:19:01 DBG] Read acquired semaphore
[14:19:01 DBG] Read completed
[14:19:01 DBG] Send 

[14:19:01 INF] Keepalive success
[14:19:01 DBG] Send acquired semaphore
[14:19:01 DBG] Send completed
[14:19:01 DBG] Read start
[14:19:01 DBG] Read acquired semaphore
[14:19:01 DBG] Read completed
[14:19:01 INF] Keepalive success
[14:19:02 DBG] Send 

[14:19:02 DBG] Send acquired semaphore
[14:19:02 DBG] Send completed
[14:19:02 DBG] Read start
[14:19:02 DBG] Read acquired semaphore
[14:19:02 DBG] Read completed
[14:19:02 DBG] Send 

[14:19:02 INF] Keepalive success
[14:19:02 DBG] Send acquired semaphore
[14:19:02 DBG] Send completed
[14:19:02 DBG] Read start
[14:19:02 DBG] Read acquired semaphore
[14:19:02 DBG] Read completed
[14:19:02 DBG] Send 

[14:19:02 INF] Keepalive success
[14:19:02 DBG] Send acquired semaphore
[14:19:02 DBG] Send completed
[14:19:02 DBG] Read start
[14:19:02 DBG] Read acquired semaphore
[14:19:02 DBG] Read completed
[14:19:02 INF] Keepalive success
[14:19:03 DBG] Send 

[14:19:03 DBG] Send acquired semaphore
[14:19:03 DBG] Send completed
[14:19:03 DBG] Read start
[14:19:03 DBG] Read acquired semaphore
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
[14:19:03 WRN] System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at maxbl4.RfidDotNet.AlienTech.Net.ByteStream.Read(String terminators) in C:\Temp\RfidDotNet-master\maxbl4.RfidDotNet.AlienTech\Net\ByteStream.cs:line 70
Exception thrown: 'maxbl4.RfidDotNet.Exceptions.ConnectionLostException' in maxbl4.RfidDotNet.AlienTech.dll
[14:19:03 DBG] Send 

[14:19:03 DBG] Send acquired semaphore
Exception thrown: 'maxbl4.RfidDotNet.Exceptions.ConnectionLostException' in mscorlib.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
[14:19:03 WRN] System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Send(Byte[] buffer)
   at maxbl4.RfidDotNet.AlienTech.Net.ByteStream.Send(String data) in C:\Temp\RfidDotNet-master\maxbl4.RfidDotNet.AlienTech\Net\ByteStream.cs:line 45
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.AggregateException' in mscorlib.dll
[14:19:03 INF] Disposing
[14:19:03 INF] Disposing
[14:19:03 INF] Disposing
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'maxbl4.RfidDotNet.Exceptions.ConnectionLostException' in maxbl4.RfidDotNet.AlienTech.dll
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Exception thrown: 'System.ObjectDisposedException' in mscorlib.dll
Exception thrown: 'System.AggregateException' in mscorlib.dll
[14:19:03 INF] Disposing
The program '[9996] WpfApp2.exe' has exited with code -1 (0xffffffff).

**Comment by maxbl4** [comment]
https://github.com/maxbl4/RfidDotNet.Wpf.Demo

**Comment by merc74** [comment]
![ErrorImage](https://user-images.githubusercontent.com/75846421/109863178-536ea780-7c2f-11eb-8475-6a34af067512.png)
it seems to read the tag at least once then it gives this error.
I'm testing this using a real Alien Antenna. The console App works without any issues with the same hardware.

2021-03-03 14:43:39> System.Exception: Unexcpected response: Error 1: Command not understood.
   at maxbl4.RfidDotNet.AlienTech.Interfaces.AlienReaderApi.<Property>d__74`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at maxbl4.RfidDotNet.AlienTech.ReconnectingAlienReaderProtocol.<<-ctor>b__40_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at maxbl4.RfidDotNet.AlienTech.ReconnectingAlienReaderProtocol.<Connect>d__42.MoveNext()

**Comment by maxbl4** [comment]
What model of reader you use? Version of firmware? "Command not understood." Is response from the reader

**Comment by merc74** [comment]
It works flawlessly with your Demo Console app
  
Function = Reader
  ReaderName = Alien RFID Reader
  ReaderType = Alien RFID Tag Reader, Model: ALR-9650 (One Antenna / Gen 2 / 902-928 MHz)
  ReaderVersion = 14.07.01.00
  DSPVersion = DSP:02.003.050-01.003.000 reader:09 country:01 radio:12 board:20
  ReaderNumber = 255
  BaudRate = 115200
  Username = alien
  MaxAntenna = 1
  AntennaSequence = 0
  RFAttenuation = 0
  RFLevel = 290
  RFModulation = DRM
  MyData = (Not Set)

MACAddress = 00:1B:5F:00:B9:33
  DHCP = OFF
  DHCPTimeout = 90
  IPAddress = 192.168.0.47
  Hostname = LLAlien
  UpgradeAddress = 0.0.0.0
  NetworkUpgrade = OFF
  Gateway = 192.168.0.1
  Netmask = 255.255.255.0
  DNS = 208.67.222.222
  NetworkTimeout = 90
  CommandPort = 23
  CommandPortLocal = 2300
  HeartbeatAddress = 255.255.255.255
  HeartbeatPort = 3988
  HeartbeatTime = 30
  HeartbeatCount = -1
  WWWPort = 80
  AcceptConnections = ANY

**Comment by merc74** [comment]
Seems that it crashes on that command: "AcqG2AntennaCombine"

It seems to be a managed exception, it will still read tags after this error.

**Comment by maxbl4** [comment]
I will check tomorrow, probably that command is not supported by your reader. I was developing against f800 model. You can try to build version without that option set.
Later i may add check for reader type

**Comment by merc74** [comment]
Is it possible to stop the logging in the output?
[00:47:29 DBG] Send acquired semaphore
[00:47:29 DBG] Send completed
[00:47:29 DBG] Read start
[00:47:29 DBG] Read acquired semaphore
[00:47:29 DBG] Read completed
[00:47:29 DBG] Read start
[00:47:29 DBG] Read acquired semaphore
[00:47:29 DBG] Read completed
[00:47:29 DBG] Send TagList?

**Comment by maxbl4** [comment]
Where do you see that output? It is written via Serilog and target is controlled by serilog config, by default it should not be visible. Maybe you have configured Serilog in your project? Then you need to customize config to exclude maxbl4.* namespaces

**Comment by maxbl4** [comment]
I've push packages version 1.0.66 without AcqG2AntennaCombine call, please check

**Comment by merc74** [comment]
Thanks for the new version that was an easy fix.
Yes I'm using SeriLog in my project, I will check into changing this configuration.

In my project I'm using BlockingCollection with ConcurrentQueue.
BlockingCollection<T> _dataQueue = new BlockingCollection<T>(new ConcurrentQueue<T>());
Using BlockingCollection is very good because when there is nothing coming in the Collection it's not using any CPU. I'm wondering if it would be possible to use that within your module. This would minimize the CPU usage for sure, but I'm not sure if it would be possible to do that with Alien communication. Instead of constantly looping the BlockingCollection waits for something to be added to collection.

**Comment by maxbl4** [comment]
Constant loop is needed anyway to work with the reader. When I was developing the first version only for Alien reader, I have implemented Alien's Tag Stream. You can tell the reader to connect back to your app's socket and push new tags as a stream. That was working fairly well, but had some disadvantages:
1. Only some Alien reader's support that mode
2. Your IP must be accessible to the reader
3. In case of lost connection, it was sometime not trivial to reconnect and restart the stream.
4. Such mode is not supported by generic serial readers and I had to implement a polling loop for them and I wanted to have more similar code in both drivers.
That's why I use polling loop, yes it consumes some CPU, but even on Orange Pi Prime (same as Raspberry Pi 3b) which I used for tests of serial reader it takes only like 30-50% of one of the cores.
And it does not matter if I use blocking collection or not, I have to run infinite loop myself to poll reader for tags as fast as possible (at least in my application, I need to reader tags ASAP). If your application is tolerant to latency, I can add parameter to configure delay in the polling loop

**Comment by merc74** [comment]
Understood, I do prefer to have the tag as fast as possible.
Turns out the command AcqTime is also not supported by 9650, I commented it out too.

**Comment by maxbl4** [comment]
You can use ReconnectingAlienProtocol directly and provide your own onConnected device setup logic
